version: '3.1'

services:
  cat-vs-dogs:
    build: .
    ports:
      - 8080:80
    restart: always
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    volumes:
        - redis_data:/data

volumes:
    redis_data: 